### ISSUE TITLE
New comment support

### ISSUE THREAD

**Issue by richxrich** [nikitaourazbaev/st4-liquid#1]
Firstly hats off to your work here, as fellow liquid coder this helps so much :) 

The new comment tas has come out, it's a game changer I think, no longer having to wrap everything in the word comment and endcomment and just able to 

`# comment like this`

Are you open to pull requests or would you rather feature requests in here?

**Comment by nikitaourazbaev** [comment]
@richxrich Thanks! It’s still a work in progress but I’m glad you find it helpful. PRs are welcome, I have this on my to-do list but probably wouldn't get to it until next week at earliest so if you'd like to give it a go feel free.
